### ISSUE TITLE
crash on some devices

### ISSUE THREAD

**Issue by flankechen** [dev-area/Android-Service#2]
some code running well on pixel and samsung s9. But crash on OPPO R11S, and VIVO X20, saying:

```
05-28 11:14:32.377 6884-6884/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: app.mabel.com.mysimpclient, PID: 6884
                                                 java.lang.NullPointerException: Attempt to invoke interface method 'int app.mabel.com.mylib.ISimp.getByteArrayLength(byte[])' on a null object reference
                                                     at app.mabel.com.mysimpclient.MainActivity$1.onClick(MainActivity.java:46)
                                                     at android.view.View.performClick(View.java:5648)
                                                     at android.view.View$PerformClick.run(View.java:22505)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:181)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6273)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
```

update:
it seems nothing to do with the api level, samsung s7 with android 7.0 runs as well, what did Chinese devices do????

**Comment by brianleePTL** [comment]
I am seeing this when trying to run on an NXP AOSP build - did you ever solve this @flankechen ?
